### ISSUE TITLE
About Us section link on Top Nav alignment to centre of page

### ISSUE THREAD

**Issue by linajin03** [SDSS-UofT/sdss-uoft.github.io#18]
<img width="1327" alt="image" src="https://github.com/SDSS-UofT/sdss-uoft.github.io/assets/53534844/b518ec38-6046-412c-a98f-6d4cdd80ec65">

**Comment by chinchinjim** [comment]
this problem shows up with each section and i think it has to do with the reveal animation messing up the spacing. the solution could be to remove it but we'd have slightly awkward spacing between sections since we wanted each section to take up its own full page view. I could take out the animations but add a scroll down button to make it less awkward between section transitions? or we could remove the individual margins/padding and add spacer divs between each section, then reference the links to the spacers instead of the actual content?
